# Generated by Django 5.0.4 on 2024-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(default='aprovado', max_length=15),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(default='debito', max_length=10),
        ),
    ]
